#!/usr/bin/env bash

set -e
#set -x
set -u

talend_baseline_policy_script_path=$(readlink -e "${BASH_SOURCE[0]}")
talend_baseline_policy_script_dir="${talend_baseline_policy_script_path%/*}"

source "${talend_baseline_policy_script_dir}/policy.sh"

declare baseline_policy
policy_public_read baseline.aws.talend.com baseline_policy
echo "${baseline_policy}" > baseline.aws.talend.com.policy
aws s3api put-bucket-policy --bucket baseline.aws.talend.com --policy "file://${talend_baseline_policy_script_dir}/baseline.aws.talend.com.policy"

